### ISSUE TITLE
noarch problem: Windows entry point isn't an .exe

### ISSUE THREAD

**Issue by tadeu** [conda-forge/restructuredtext_lint-feedstock#4]
When in Windows, the entry point (installed in %CONDA_PREFIX%\Scripts) is called only `rst-lint` and is not executable, it should've been `rst-lint.exe`.

**Comment by moorepants** [comment]
I believe the entry point needs to be specified in the conda recipe to ensure proper builds with noarch, it can't solely rely on the setup.py spec.

**Comment by dopplershift** [comment]
Fixed by #8.
